# Generated by Django 4.2.21 on 2025-06-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_at'], name='app_questio_created_eedfc6_idx'),
        ),
    ]
