# Generated by Django 5.0.4 on 2025-06-15 12:06

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_question_app_questio_created_eedfc6_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='question',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('title', 'content', config='russian'), name='question_search_idx'),
        ),
    ]
